# /.github/workflows/docker-publish.yml

name: CI/CD - Publicar Imagens Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push API E-commerce
      uses: docker/build-push-action@v4
      with:
        context: ./api-ecommerce
        push: true
        tags: viniciuscx/tech-store-devops-api:latest # TROQUE 'viniciuscribeiro'

    - name: Build and push AI Service
      uses: docker/build-push-action@v4
      with:
        context: ./servico-ia
        push: true
        tags: viniciuscx/tech-store-devops-ia:latest # TROQUE 'viniciuscribeiro'

    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: viniciuscx/tech-store-devops-frontend:latest # TROQUE 'viniciuscribeiro'